version: "3.8"
services:
  angular-frontend:
    build:
      context: ./viajesExpress
      dockerfile: Dockerfile
    ports:
      - "4200:80"
    depends_on:
      - spring-backend

  spring-backend:
    build:
      context: ./expressbackend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - DB_URL=jdbc:mysql://host.docker.internal:3306/tu_basededatos
      - DB_USERNAME=root
      - DB_PASSWORD=